### ISSUE TITLE
`method: :delete` link and inline form that it generates

### ISSUE THREAD

**Issue by GBH** [phoenixframework/phoenix_html#151]
Phoenix v.1.3-rc

Right now link with `method: delete` will generate a form that is getting inlined right next to it. This creates a problem if you put that delete link somewhere inside an existing form. This will effectively nest forms. Invalid html aside, it will trigger delete action when you just want to submit your original form. Not expected. 

I believe Rails used to have the same mechanism before v3. Now it creates form on click and puts in somewhere at the end of the `<body>` so it doesn't interfere with things. See: https://github.com/rails/jquery-ujs/blob/master/src/rails.js#L210 (Rails5 moved from jquery, but it's the same idea)

Thoughts?

**Comment by josevalim** [comment]
@GBH :+1: for this change since we depend on JavaScript anyway. If we do this though, we should probably stop using data-submit="parent" and also rely on data-method="...".

PR please?

**Comment by almielczarek** [comment]
If no one is working on this, I think I know what to do to to correct this behavior. Let me know!

**Comment by GBH** [comment]
@almielczarek it's all yours. I'm not much of a javascript person.

**Comment by josevalim** [comment]
Fixing in favor of the PR.

**Comment by ckruse** [comment]
This is a pretty breaking change. I relied on the inline forms. I guess there is no way to get back the old behavior but write my own helper with the same API as the old one?

**Comment by josevalim** [comment]
@ckruse you can also depend on the previous version explicitly for now. Is there any reason why you would prefer the form version? Given it has limitations regarding nesting?

**Comment by ckruse** [comment]
Pinning the version seems like a problem in the long run.

I relied on the inline form solution because it easily allowed me to create buttons for non-get requests without relying on JS. I develop everything with progressive enhancement in mind, this also means: if you don't have JS the application should still at least continue to work.

The assumption that the user don't has JS comes in different forms: he may have turned it off (NoScript extension?), he may have a bad internet connection and thus it hasn't been loaded yet, the client may be incapable of features like `querySelector()` et al, etc, pp.

It also is not true that one already has to have JS to use applications built with Phoenix, I am maintaining an application where JS is optional. It behaves different and is not as nice to use as with JS, but it works.

**Comment by josevalim** [comment]
Thanks for the explanation and apologies for not considering those use cases. One last question, didn't the previous version use data-submit=parent though which required javascript?

**Comment by ckruse** [comment]
No need to apologize! This wasn't meant as a complaint, I totally rely on your and Chris' work and think you are doing a great job, thanks for all the hard work!

Regarding JS: I don't think so. The code the old function generates looks as follows:

~~~
<form action="/admin/users/2" class="button" method="post">
  <input name="_method" type="hidden" value="delete">
  <input name="_csrf_token" type="hidden" value="Tho4KCZvAxk8ABEqATdgEzNfHz5EEAAAzrBqa+qWucpM8MUer2fqkg==">
  <button class="destructive-index-action" data-confirm="Sind Sie sicher?" type="submit">Löschen</button>
</form>
~~~

**Comment by ckruse** [comment]
The `data-confirm` is handled by my own code, though. I don't even include the Phoenix JS code.

**Comment by AlmogRnD** [comment]
I'm having the same issue has then been fixed? Not working on my end using latest version

**Comment by ckruse** [comment]
I ended up writing my own button helpers for form based delete buttons.

**Comment by AlmogRnD** [comment]
Thanks I can't do that I'm using the mix generator and the delete button is not working there
