### ISSUE TITLE
Tag attribute constraint

### ISSUE THREAD

**Issue by joshuaflores** [phoenixframework/phoenix_html#185]
file: /lib/phoenix_html/tag.ex
line: 11

There seems to be a constraint on the options that can be traversed by `Tag.build_attrs/3` to only those set by `@tag_prefixes`. The question is why the constraint? I have removed `@tag_prefixes` and changed `Tag.build_attrs/3` to run if the key value can be traversed, and it seems to work just as well. The only issue I can find is that `link_test.exs:34` fails.

I'm fairly certain that this would be an easy fix but before I submit a pr I was wondering if there was something I'm missing.

Thanks.

**Comment by josevalim** [comment]
@joshuaflores it is not that straight-forward. This is a valid attribute: `class: ["foo", " ", "bar"]`. If you try to traverse everything, you will run into cases where attributes are given as an IO list, which are traversible, but do not work like `data`/`aria` attributes. That's why the link test fails (and it fails correctly). :)

**Comment by joshuaflores** [comment]
@josevalim thanks I was sure there was a good reason. Also thank you for all the work you do in the community, it's truly incredible.
