### ISSUE TITLE
Support inputs_for_struct to facilitate prefilling self defined Ecto.Types in forms

### ISSUE THREAD

**Issue by Blackjaguar18** [phoenixframework/phoenix_html#230]
This question arises from having multiple self defined Ecto.Type structs within an embedded field of a parent Ecto struct. If I render a form with an `%Ecto.Changeset{}` of a populated model, the fields belonging to the self defined struct are not pre filled.
I am not even sure if this is something desirable, or if I am missing something completely here.

Expected functionality:
An `inputs_for_struct` block can contain any of the already existing Phoenix.HTML input functions, leaving the programmer in control which fields of the struct to display.  This would then result into a form where the input fields are correctly extracted and filled from the provided changeset and any default/existing values are shown.

N.B. I would be happy to contribute to this and make a pr if the above approach is reasonable!

**Comment by josevalim** [comment]
Hi @Blackjaguar18! Thanks for opening an issue.

I am not sure if `inputs_for_struct` is the best way to go. My recommendation would be to play a bit around with the `phoenix_ecto` project and maybe check if it can work out of the box there. That's because `inputs_for` doesn't do much work, it just delegates to the changeset+html implementation found in `phoenix_ecto`. So we may be able to fix without touching this project.

**Comment by Blackjaguar18** [comment]
@josevalim Thanks for the reply, I will have a look into that!

**Comment by josevalim** [comment]
Ping. :)

**Comment by Blackjaguar18** [comment]
@josevalim Sorry for my late reply! I managed to fix this without the need to touch any project by using a different approach entirely. This issue can be closed as far as I am concerned.

**Comment by josevalim** [comment]
Thanks for the follow up!
