### ISSUE TITLE
Proposal: conditionally setting css classes

### ISSUE THREAD

**Issue by wojtekmach** [phoenixframework/phoenix_html#276]
It's pretty common to end up with code like this:

```eex
<%= link_to "Home", "/", class: (["button"] ++ (if path == "/", do: ["active"], else: []) %>
```

I'd like to propose to allow passing a map of `class => true|false` to conditionally include a given class instead:

```eex
<%= link_to "Home", "/", class: %{"button" => true, "active" => path == "/"} %>
```

Another idea would be:

```eex
<%= link_to "Home", "/", class: ["button", {"active", path == "/"}] %>
```

**Comment by wojtekmach** [comment]
I think this syntax would be the nicest:

```elixir
class: ["button", "active": path == "/"]
```

but the problem is it creates an atom so if someone does this:

```elixir
class: ["button", "user_#{id}": path == "/"]
```

they could blow up their atom table.

I agree what I proposed is a bit awkward to use, curious if folks come up with other ideas!

**Comment by tomekowal** [comment]
I have a similar but slightly different problem and I was also thinking about potential solutions.
I have lots of tables in one of my projects and wanted to create view helpers for them but they often differ slightly.

By default I want this:

```html
<table class="table">
```

But in one place I need:

```html
<table calss="table table-striped">
```

and in other I need:

```html
<table class="table table-dark">
```

I imagined a solution that would allow for composing HTML before producing io list like this.

```elixir
table() |> add_class("table-dark")
```

or for @wojtekmach example

```elixir
<%= link_to("Home", "/", class: "button") |> maybe_add_active_class(path, "/") %>
```

That is currently impossible because all `Phoenix.HTML` functions return the io lists directly. For composition to work, we would need an intermediate data structure that we can construct step by step and that implements `Phoenix.HTML.Safe`

I started a discussion on Elixir Forum and presented my reasoning
https://elixirforum.com/t/would-you-find-composablehtml-library-useful

Unfortunately, it would require rewriting `Phoenix.HTML.{Link, Form, Tag}` to support composition, so you may find that option not viable.

On the other hand, this would help keep the templating language clean and simple.

**Comment by wojtekmach** [comment]
Looking at it again, I think this is actually not bad:

```elixir
iex> active? = false
iex> link("Home", to: "/", class: ["btn", active? && "active"]) |> Phoenix.HTML.safe_to_string() |> IO.puts()
<a class="btnactive" href="/">Home</a>
```

note, the intention was to have have 2 separate classes, not one class. Perhaps we can't change it as the user may want to pass an iolist. In this case a simple solution is to add leading/trailing spaces:

```elixir
iex> Phoenix.HTML.Link.link("Home", to: "/", class: ["btn", active? && " active"]) |> Phoenix.HTML.safe_to_string() |> IO.puts()
<a class="btn active" href="/">Home</a>
```

the problem however is currently nil is not accepted:

```elixir
iex> active? = false
iex> link("Home", to: "/", class: ["btn", active? && " active"]) |> Phoenix.HTML.safe_to_string() |> IO.puts
** (ArgumentError) lists in Phoenix.HTML and templates may only contain integers representing bytes, binaries or other lists, got invalid entry: nil
```

---

@chrismccord maybe this is where `class/1` comes in? I could see:

```
iex> class(["foo"])
["foo"]

iex> class(["foo", "bar"])
["foo", 32, "bar"] # iolist that means "foo bar"

iex> class(["foo", nil])
["foo"]

iex> class(["foo", false])
["foo"]
```

**Comment by tomekowal** [comment]
@wojtekmach Your last approach with `&&` almost works. It is only missing the default after `||`.

```Elixir
iex> active? = false
iex> link("Home", to: "/", class: ["btn", active? && " active" || ""]) |> Phoenix.HTML.safe_to_string() |> IO.puts
<a class="btn" href="/">Home</a>
```

It uses the fact that `&&` and `||` short circuit and that `["btn", ""]` is an io list that gets flattened to `"btn"`

That can be easily put as a helper in view helpers:

```Elixir
def maybe_attr_value(value, condition) do
  if condition, do: [?\s, value], else: ""
end
```

That would work for classes, styles and all other attributes.

@chrismccord You mentioned that order must be respected. Is it also the case for data attributes? I am asking because they seem to be sorted alphabetically:

```Elixir
iex> IO.puts Phoenix.HTML.safe_to_string Phoenix.HTML.Tag.tag(:p, [data: [z: "z", a: "a"]])
<p data-a="a" data-z="z">
```

**Comment by wojtekmach** [comment]
I think there would not be a need for maybe_attr_value/2 if there’s a class/1 described above (or data passed to `:class` key behaves like that.) I mean, I agree that maybe_attr_value/2 would work for any attribute, not just class, it’s just didn’t come up in my work nearly often enough as for classes.

**Comment by tomekowal** [comment]
I agree that classes are the most popular. Another one that could use similar helper would be `style`. Conditional styling also pops up from time to time.

**Comment by josevalim** [comment]
Given next version will be v3.0, it is the perfect opportunity to introduce this feature. The idea is to allow a list to be given and, if a list is given, any false or nil at the root are removed. Would that be a fair description?

My only pending question is: should we do it for all attributes or only certain ones?

**Comment by josevalim** [comment]
Btw, we should also add a public `html_attributes_to_iodata` function. :)
